// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuAgAjCV7oGEmMNDXScpt2uyuBU1A83OY',
    appId: '1:66599944798:web:e061cf320968ff3ef26acf',
    messagingSenderId: '66599944798',
    projectId: 'registrousuarios-a2cca',
    authDomain: 'registrousuarios-a2cca.firebaseapp.com',
    storageBucket: 'registrousuarios-a2cca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMCbKkXtoyOu4fqSylNPSl-UjTMjUO5zA',
    appId: '1:66599944798:android:d93b2fdc51498b21f26acf',
    messagingSenderId: '66599944798',
    projectId: 'registrousuarios-a2cca',
    storageBucket: 'registrousuarios-a2cca.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuAgAjCV7oGEmMNDXScpt2uyuBU1A83OY',
    appId: '1:66599944798:web:8ae3fe8ca7f127bef26acf',
    messagingSenderId: '66599944798',
    projectId: 'registrousuarios-a2cca',
    authDomain: 'registrousuarios-a2cca.firebaseapp.com',
    storageBucket: 'registrousuarios-a2cca.appspot.com',
  );
}
